name = "rss-feishu-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Cron Trigger - 每15分钟检查一次
[triggers]
crons = ["*/15 * * * *"]

# KV 命名空间用于存储已推送的记录
[[kv_namespaces]]
binding = "PUSHED_ITEMS"
id = "4d53e8987f3a456e9ca3e6496737c24b"
preview_id = "a1eabd2a2fe64ac680e56fff694ef2ae"
